In [3]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import csv

In [41]:
df = pd.read_csv(r'C:/Users/Manjunath/Desktop/practice/01-Petrol_consumption.csv')


In [42]:
df.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

In [43]:
df.shape

(48, 5)

In [44]:
df.isnull().sum()

Petrol_tax                      0
Average_income                  0
Paved_Highways                  0
Population_Driver_licence(%)    0
Petrol_Consumption              0
dtype: int64

In [45]:
df.dtypes

Petrol_tax                      float64
Average_income                    int64
Paved_Highways                    int64
Population_Driver_licence(%)    float64
Petrol_Consumption                int64
dtype: object

In [62]:
#Seperate X and y values
X = df.iloc[:,:-1].values 
y = df.iloc[:,-1].values

In [63]:
X

array([[9.0000e+00, 3.5710e+03, 1.9760e+03, 5.2500e-01],
       [9.0000e+00, 4.0920e+03, 1.2500e+03, 5.7200e-01],
       [9.0000e+00, 3.8650e+03, 1.5860e+03, 5.8000e-01],
       [7.5000e+00, 4.8700e+03, 2.3510e+03, 5.2900e-01],
       [8.0000e+00, 4.3990e+03, 4.3100e+02, 5.4400e-01],
       [1.0000e+01, 5.3420e+03, 1.3330e+03, 5.7100e-01],
       [8.0000e+00, 5.3190e+03, 1.1868e+04, 4.5100e-01],
       [8.0000e+00, 5.1260e+03, 2.1380e+03, 5.5300e-01],
       [8.0000e+00, 4.4470e+03, 8.5770e+03, 5.2900e-01],
       [7.0000e+00, 4.5120e+03, 8.5070e+03, 5.5200e-01],
       [8.0000e+00, 4.3910e+03, 5.9390e+03, 5.3000e-01],
       [7.5000e+00, 5.1260e+03, 1.4186e+04, 5.2500e-01],
       [7.0000e+00, 4.8170e+03, 6.9300e+03, 5.7400e-01],
       [7.0000e+00, 4.2070e+03, 6.5800e+03, 5.4500e-01],
       [7.0000e+00, 4.3320e+03, 8.1590e+03, 6.0800e-01],
       [7.0000e+00, 4.3180e+03, 1.0340e+04, 5.8600e-01],
       [7.0000e+00, 4.2060e+03, 8.5080e+03, 5.7200e-01],
       [7.0000e+00, 3.7180e+03,

In [64]:
y

array([541, 524, 561, 414, 410, 457, 344, 467, 464, 498, 580, 471, 525,
       508, 566, 635, 603, 714, 865, 640, 649, 540, 464, 547, 460, 566,
       577, 631, 574, 534, 571, 554, 577, 628, 487, 644, 640, 704, 648,
       968, 587, 699, 632, 591, 782, 510, 610, 524], dtype=int64)

In [65]:
# split using train_test_split from model_selection
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [66]:
X_train

array([[7.5000e+00, 5.1260e+03, 1.4186e+04, 5.2500e-01],
       [7.0000e+00, 3.3330e+03, 6.5940e+03, 5.1300e-01],
       [7.5000e+00, 3.3570e+03, 4.1210e+03, 5.4700e-01],
       [7.5000e+00, 3.8460e+03, 9.0610e+03, 5.7900e-01],
       [7.0000e+00, 5.0020e+03, 9.7940e+03, 5.9300e-01],
       [9.0000e+00, 3.8650e+03, 1.5860e+03, 5.8000e-01],
       [7.0000e+00, 4.2960e+03, 4.0830e+03, 6.2300e-01],
       [7.0000e+00, 4.7160e+03, 5.9150e+03, 7.2400e-01],
       [7.0000e+00, 4.3180e+03, 1.0340e+04, 5.8600e-01],
       [8.0000e+00, 4.1880e+03, 5.9750e+03, 5.6300e-01],
       [9.0000e+00, 4.8970e+03, 2.4490e+03, 5.1100e-01],
       [7.0000e+00, 4.2060e+03, 8.5080e+03, 5.7200e-01],
       [7.0000e+00, 3.6560e+03, 3.9850e+03, 5.6300e-01],
       [7.0000e+00, 4.5930e+03, 7.8340e+03, 6.6300e-01],
       [7.0000e+00, 4.3000e+03, 3.6350e+03, 6.0300e-01],
       [8.0000e+00, 4.4470e+03, 8.5770e+03, 5.2900e-01],
       [7.0000e+00, 4.2070e+03, 6.5800e+03, 5.4500e-01],
       [9.0000e+00, 3.7210e+03,

In [67]:
y_train

array([471, 554, 628, 631, 524, 561, 610, 865, 635, 574, 464, 603, 699,
       649, 632, 464, 508, 566, 457, 714, 644, 566, 648, 524, 525, 591,
       460, 344, 547, 640, 540, 640, 498, 968, 510, 414, 541, 782],
      dtype=int64)

In [68]:
# import LinearRegression from linear_model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [69]:
# Create and fit the model
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [70]:
#bias(b)
model.intercept_

425.59933220324103

In [71]:
#slope/weight (w)
model.coef_

array([-4.00166602e+01, -6.54126674e-02, -4.74073380e-03,  1.34186212e+03])

In [72]:
#Predict
y_pred = model.predict(X_test)

In [73]:
y_pred

array([469.39198872, 545.64546431, 589.66839402, 569.7304133 ,
       649.77480909, 646.63116356, 511.60814841, 672.47517717,
       502.07478157, 501.2707342 ])

In [74]:
y_test

array([534, 410, 577, 571, 577, 704, 487, 587, 467, 580], dtype=int64)

In [75]:
#r2_score from metrics
from sklearn.metrics import r2_score

In [76]:
score = r2_score(y_test,y_pred)

In [77]:
score

0.20361932410121653