In [5]:
#importing libraries
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import csv

In [13]:
df = pd.read_csv(r'C:\Users\Manjunath\Desktop\practice\02-Load_Boston.csv')
df

Unnamed: 0     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  \
0             0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1             1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2             2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3             3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4             4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   
..          ...      ...   ...    ...   ...    ...    ...   ...     ...  ...   
501         501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1   
502         502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1   
503         503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1   
504         504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1   
505         505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1   

     TAX  PTRATIO       B  LSTAT  TARGET  
0    296     15.3  396.90   4.98    24.0  
1    242     17.8  396.90   9.14    21.6  
2    242     17.8  392.83   4.03    34.7  
3    222     18.7  394.63   2.94    33.4  
4    222     18.7  396.90   5.33    36.2  
..   ...      ...     ...    ...     ...  
501  273     21.0  391.99   9.67    22.4  
502  273     21.0  396.90   9.08    20.6  
503  273     21.0  396.90   5.64    23.9  
504  273     21.0  393.45   6.48    22.0  
505  273     21.0  396.90   7.88    11.9  

[506 rows x 15 columns]

In [14]:
df.head()

Unnamed: 0     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  \
0           0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1           1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2           2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3           3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4           4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   

   TAX  PTRATIO       B  LSTAT  TARGET  
0  296     15.3  396.90   4.98    24.0  
1  242     17.8  396.90   9.14    21.6  
2  242     17.8  392.83   4.03    34.7  
3  222     18.7  394.63   2.94    33.4  
4  222     18.7  396.90   5.33    36.2

In [15]:
df.isnull().sum()

Unnamed: 0    0
CRIM          0
ZN            0
INDUS         0
CHAS          0
NOX           0
RM            0
AGE           0
DIS           0
RAD           0
TAX           0
PTRATIO       0
B             0
LSTAT         0
TARGET        0
dtype: int64

In [19]:
x = df.iloc[:,:-1].values 
y = df.iloc[:,-1].values

In [20]:
x

array([[0.0000e+00, 6.3200e-03, 1.8000e+01, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [1.0000e+00, 2.7310e-02, 0.0000e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.0000e+00, 2.7290e-02, 0.0000e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [5.0300e+02, 6.0760e-02, 0.0000e+00, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [5.0400e+02, 1.0959e-01, 0.0000e+00, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [5.0500e+02, 4.7410e-02, 0.0000e+00, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [21]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [25]:
x_train

array([[2.2000e+02, 3.5809e-01, 0.0000e+00, ..., 1.7400e+01, 3.9170e+02,
        9.7100e+00],
       [7.1000e+01, 1.5876e-01, 0.0000e+00, ..., 1.9200e+01, 3.7694e+02,
        9.8800e+00],
       [2.4000e+02, 1.1329e-01, 3.0000e+01, ..., 1.6600e+01, 3.9125e+02,
        1.1380e+01],
       ...,
       [1.1700e+02, 1.5098e-01, 0.0000e+00, ..., 1.7800e+01, 3.9451e+02,
        1.0300e+01],
       [4.7000e+01, 2.2927e-01, 0.0000e+00, ..., 1.7900e+01, 3.9274e+02,
        1.8800e+01],
       [1.7200e+02, 1.3914e-01, 0.0000e+00, ..., 1.6600e+01, 3.9690e+02,
        1.4690e+01]])

In [26]:
y_train

array([26.7, 21.7, 22. , 22.9, 10.4, 21.9, 20.6, 26.4, 41.3, 17.2, 27.1,
       20.4, 16.5, 24.4,  8.4, 23. ,  9.7, 50. , 30.5, 12.3, 19.4, 21.2,
       20.3, 18.8, 33.4, 18.5, 19.6, 33.2, 13.1,  7.5, 13.6, 17.4,  8.4,
       35.4, 24. , 13.4, 26.2,  7.2, 13.1, 24.5, 37.2, 25. , 24.1, 16.6,
       32.9, 36.2, 11. ,  7.2, 22.8, 28.7, 14.4, 24.4, 18.1, 22.5, 20.5,
       15.2, 17.4, 13.6,  8.7, 18.2, 35.4, 31.7, 33. , 22.2, 20.4, 23.9,
       25. , 12.7, 29.1, 12. , 17.7, 27. , 20.6, 10.2, 17.5, 19.7, 29.8,
       20.5, 14.9, 10.9, 19.5, 22.7, 19.5, 24.6, 25. , 24.5, 50. , 14.3,
       11.8, 31. , 28.7, 16.2, 43.5, 25. , 22. , 19.9, 22.1, 46. , 22.9,
       20.2, 43.1, 34.6, 13.8, 24.3, 21.5, 24.4, 21.2, 23.8, 26.6, 25.1,
        9.6, 19.4, 19.4,  9.5, 14. , 26.5, 13.8, 34.7, 16.3, 21.7, 17.5,
       15.6, 20.9, 21.7, 12.7, 18.5, 23.7, 19.3, 12.7, 21.6, 23.2, 29.6,
       21.2, 23.8, 17.1, 22. , 36.5, 18.8, 21.9, 23.1, 20.2, 17.4, 37. ,
       24.1, 36.2, 15.7, 32.2, 13.5, 17.9, 13.3, 11

In [27]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [28]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [29]:
model.intercept_

38.072455255670306

In [30]:
model.coef_

array([-1.53342064e-03, -1.20147371e-01,  4.62737609e-02,  4.90615359e-03,
        2.36312905e+00, -1.59956753e+01,  3.72664697e+00, -4.37222012e-03,
       -1.40118535e+00,  2.54983389e-01, -1.05377076e-02, -1.04140137e+00,
        8.10317942e-03, -4.93940048e-01])

In [31]:
y_pred = model.predict(X_test)

In [32]:
y_pred

array([24.74070851, 23.80425049, 29.28158723, 12.12272669, 21.62544501,
       19.53672919, 20.41968384, 21.07907383, 18.71561373, 20.09106627,
        5.0743656 , 16.39199315, 17.04586558,  5.59756086, 40.1004106 ,
       32.44594537, 22.37310101, 36.90219137, 30.92296454, 23.38467089,
       24.56769934, 24.68964766, 20.74869698, 30.26277533, 22.5727197 ,
       10.26862735, 17.85459566, 18.35674777, 35.63890106, 21.10275378,
       18.19893242, 17.74077459, 19.8424078 , 23.9617786 , 29.10081048,
       19.4061865 , 11.16022961, 24.69300159, 17.57248617, 15.3845642 ,
       26.02409131, 21.01278459, 22.13029338, 15.48998891, 22.73582152,
       25.34879667, 19.85072994, 23.01557869, 10.10805363, 24.46214312,
       21.07023089, 16.9730934 , 24.46656588, 29.93880071, 13.52902169,
       21.98895501, 20.5438668 , 15.18210672, 13.9690285 , 22.08542847,
       17.53668953, 21.36714506, 32.83463582, 31.14026148, 17.67033113,
       32.885481  , 18.66904252, 19.97300004, 19.04270401, 22.87

In [33]:
y_test

array([22.6, 50. , 23. ,  8.3, 21.2, 19.9, 20.6, 18.7, 16.1, 18.6,  8.8,
       17.2, 14.9, 10.5, 50. , 29. , 23. , 33.3, 29.4, 21. , 23.8, 19.1,
       20.4, 29.1, 19.3, 23.1, 19.6, 19.4, 38.7, 18.7, 14.6, 20. , 20.5,
       20.1, 23.6, 16.8,  5.6, 50. , 14.5, 13.3, 23.9, 20. , 19.8, 13.8,
       16.5, 21.6, 20.3, 17. , 11.8, 27.5, 15.6, 23.1, 24.3, 42.8, 15.6,
       21.7, 17.1, 17.2, 15. , 21.7, 18.6, 21. , 33.1, 31.5, 20.1, 29.8,
       15.2, 15. , 27.5, 22.6, 20. , 21.4, 23.5, 31.2, 23.7,  7.4, 48.3,
       24.4, 22.6, 18.3, 23.3, 17.1, 27.9, 44.8, 50. , 23. , 21.4, 10.2,
       23.3, 23.2, 18.9, 13.4, 21.9, 24.8, 11.9, 24.3, 13.8, 24.7, 14.1,
       18.7, 28.1, 19.8])

In [34]:
from sklearn.metrics import r2_score

In [35]:
score = r2_score(y_test,y_pred)

In [36]:
score

0.5914577039362046